### ISSUE TITLE
Find a way to power the board 

### ISSUE THREAD

**Issue by adv0r** [MADE-barcelona/beacon-fi#3]
Currently having issue with coin batteries

**Comment by willblev** [comment]
We know that 2 alkaline AA batteries in series works (provides ~3.4-3.8V)

**Comment by willblev** [comment]
As you know, the design of the current board includes 2 coin battery clips. The decision to use coin batteries as opposed to 2xAA or a lipo was for several reasons:
1) we wanted a small form factor
2) the two CR2032 batteries will _in theory_ provide the necessary voltage/current (>=2.8v, 60-70mA)
3) they are cheaper than alternatives
4) several projects exist with the ESP8266 that used coin cells, and reported long battery life... the one our project was based off of: https://medium.com/@kstevica/how-to-build-an-open-wifi-finder-using-esp8266-and-two-coin-batteries-9c31eb6f9859#.83j04caih
5) I did a simple test where I connected the ESP8266 to 2 coin batteries, and it stayed on for over 8h... HOWEVER, as this was pre-prototyping phase, the chip wasn't running any code (and therefore consumed less)

When we tried to run our prototype on these two coin cells and the new code, we noticed that the voltage of the coin cells dropped sharply and the chip turned off after a few seconds. This may be because we got the cheapest Chinese batteries we could find. Despite the fact that numerous projects had reported that the ESP8266 works with 2xcoin cell batteries, our cheap coin cells aren't enough to power the ESP8266 :-( We tried with different coin cells, and they didn't work either. After some investigation, I found this resource which explained the problem (from http://benlo.com/esp8266/KankunSmartPlug.html) :

> When it is on, the ESP8266 can be power hungry, averaging around 70 mA. A CR2032 battery will typically supply 225 mAH. Normally, the ESP8266 can connect to a server and deliver its message in less than 5 seconds. 
> 
> Then again, sometimes reality intervenes and what appears at first glance to be theoretically possible turns out in practice to be impractical. The actual discharge curve of a CR2032 battery depends on the current drain. So, draining at high current, reduces the life of the battery considerably. Not only that, but the voltage drops quite quickly once the battery is not new and falls below the operating voltage of the radio portion of the ESP8266. The microprocessor in the esp8266 will run on 1.8 volts, but the radio requires a nominal 3.3 volts.

This means that for our purposes (we will be using the 'radio' very frequently), the coin batteries are pretty much useless. The good news is that we know that two alkaline AA batteries will work; when connected in series, this gives us 3.8v/3400mAh+. However, this would mean that we would have to fit two AA batteries inside the case, or have them attached to the outside of the case somehow. Alternatively, we can get LiPo batteries that are smaller, but they won't be easy for the kids to recharge/replace later and they are 10x more expensive.

EDIT[nico]: edited original message to separate Markdown lines from text, avoiding transforming the text in header1

**Comment by adv0r** [comment]
Great report @willblev : at this we are left with two choices
1. Use AA Batteries and come up with a solution for package (external)
2. Use LiPo Batteries 
3. _[other solutions we are not thinking of]_

---

In case we go with 1. , what can we do to make the external package : 
- easy to connect to the inside of the box
- aesthetically decent
- robust  (they will be running around with the thing)

Moreover, what will we do with the coin-battery slots on the board

---

In case we go with 2. , can you please link to a battery you had in mind so we can check prices, or at least get one of them?

Are they rechargeable?

---

Another silly question : can't we make series of coins?

**Comment by willblev** [comment]
Each coin is ~3.3v... operating voltage of ESP8266 is 2.8-3.8ish. If we connect 2 batteries in series, we risk burning up the chip

**Comment by adv0r** [comment]
> we risk burning up the chip 

Can we built a quick circuit to stabilise-reduce voltage ?

PS: I edited my message above while you where replying... there are more dumb questions to answer now

**Comment by willblev** [comment]
LiPo batteries are ideal for this sort of thing as they keep voltage more or less constant and only have a sharp decrease right before they die. However, they're expensive, hard to charge, and wasteful if the kids can't reuse them. We could experiment with 2xAA and 2xAAA and see how much runtime we get in the field (both output 3.6v, but AA have double mAh).

**Comment by willblev** [comment]
@adv0r - I used to know Markdown syntax when I worked more with R/sweave/knitr, but have since forgotten everything. Will work on it.

**Comment by willblev** [comment]
> Can we built a quick circuit to stabilise-reduce voltage ?

A: Yes, (except for the 'quick' part) but most voltage regulators would waste even more power. The cheapest/easiest solution I can see is to use 2xAAA batteries (which are small enough to fit inside most boxes too). The only tricky thing is to have 25 2xAAA battery clips delivered and soldered ASAP. Something like this: http://www.batteryholders.com/part.php?pn=BC22AAAW&original=AAA&override=AAA

**Comment by adv0r** [comment]
I guess we can buy those batteryholder if needed. It s definitely cheaper than having to do it by hand. (everything we spend from this point on, is simply taken out of our pay...)

Should I buy 4AAA to make some tests ? 

We should ask Xavi if they fit in the boxes he built...

In case they don't we have to figure out an external solution that can be easily and reliably be applied on the adventure day . (or the day earlier?)

**Comment by willblev** [comment]
It may be worth purchasing an Xacto knife in case we need to do box surgery...

**Comment by adv0r** [comment]
will take a walk to diotronic sooon
