### ISSUE TITLE
Adjust the LED blink function

### ISSUE THREAD

**Issue by adv0r** [MADE-barcelona/beacon-fi#4]
Currently the blink function doesn't behave as expected.

A blink should turn on the LED and turn it off immediately.

**Comment by adv0r** [comment]
we should create a function with two inputs 
`blink (speed, duration)`

that makes the LED start a  blinking  burst for _duration_ seconds at speed _speed_ (from 0 to 10)  . 
Speed : 0 ---> don't blink
Speed : 1 ---> blink every xxx ms 
.
.
.
Speed : 1 ---> blink every yyy ms 

Speed:10 ---> always on

**Comment by willblev** [comment]
@adv0r - why would we want a 'duration parameter'? isn't the goal to have the LED blink all the time [except when there is no appropriate signals]?

I think its easier to just have one parameter, blink_speed, and this is based off signal strength... for example, when strength <= -90, we transform -90 into a blink_speed = 10,000ms (10 seconds). This means that the tmr.alarm for the blink_LED function would be set with an interval of blink_speed, or blink_speed/2 (so that the LED cycles on and off in 10sec total)

**Comment by willblev** [comment]
If you want to 'bin' blink speed by signal strength, I understand your thought process, like this: 
*0 to -20  = 100ms
*-20 to -30 = 200ms
*-30 to -35 = 300ms
etc...

But this is not necessarily a better approach than linearizing the raw -dB of rssi to a value between 100ms and 2000ms. I came up with the formula of  (rssi*rssi)/5  to do this:  http://rechneronline.de/function-graphs/  

![graph php](https://cloud.githubusercontent.com/assets/5909997/10793963/592438f2-7d93-11e5-87d7-af82ea6641a1.png)
_x axis is rssi (in dB) of the AP [tends to be between -90 and -30], y axis is ms_
